language: python

matrix:
  include:
    - name: "Python 3.11 on Linux"
      python: "3.11"
      dist: focal
    - name: "Python 3.11 on macOS"
      os: osx
      osx_image: xcode13.2
      language: shell
      before_install:
        - brew update
        - brew install python@3.11
      env: PATH="/usr/local/opt/python@3.11/bin:$PATH"
    - name: "Python 3.11 on Windows"
      os: windows
      language: shell
      before_install:
      - choco install python --version 3.11.0 -y
      - set PATH=C:\Python311;%PATH%
      env: PATH="/c/Python311:/c/Python311/Scripts:$PATH"
      
script:
  - python main.py
